name: video_clipper_app
description: A high-performance video clipper application.
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & State
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  
  # Media
  video_player: ^2.8.1
  chewie: ^1.7.4
  
  # IO
  file_picker: ^10.3.10
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  flutter_local_notifications: ^19.0.0
  wakelock_plus: ^1.1.4
  ffmpeg_kit_flutter_new: ^4.1.0
  gal: ^2.3.2
  shared_preferences: ^2.5.3
  android_intent_plus: ^6.0.0
  crypto: ^3.0.7
  photo_manager: ^3.8.3
  photo_manager_image_provider: ^2.2.0
  font_awesome_flutter: ^10.9.1
  device_info_plus: ^12.3.0
  flutter_background_service: ^5.1.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
